image: Visual Studio 2017
version: git-appveyor-{build}
before_build:
  - choco install winflexbison3
  - git clone --recursive https://github.com/thpatch/thtk.git C:\projects\thtk
  - cd C:\projects\thtk
  - cmake .
  - dir
configuration: Debug
build:
  project: C:\projects\thtk\Touhou Toolkit.sln
  verbosity: minimal
after_build:
  - dir
  - 7z a -tzip C:\projects\thtk.zip .\Debug\*
artifacts:
  path: C:\projects\thtk.zip
  name: Touhou Toolkit (git)