image: Visual Studio 2017
version: git-appveyor-{build}
before_build:
  - choco install winflexbison3
  - git clone --recursive https://github.com/thpatch/thtk.git C:\projects\thtk
  - cd C:\projects\thtk
  - cmake .
  - dir
configuration: Debug
build:
  project: C:\projects\thtk\Touhou Toolkit.sln
  verbosity: minimal
after_build:
  - dir
  - mkdir C:\projects\thtk\mybin
  - cd C:\projects\thtk\mybin
  - copy C:\projects\thtk\thanm\Debug\*.* C:\projects\thtk\mybin
  - copy C:\projects\thtk\thdat\Debug\*.* C:\projects\thtk\mybin
  - copy C:\projects\thtk\thecl\Debug\*.* C:\projects\thtk\mybin
  - copy C:\projects\thtk\thmsg\Debug\*.* C:\projects\thtk\mybin
  - copy C:\projects\thtk\thstd\Debug\*.* C:\projects\thtk\mybin
  - copy C:\projects\thtk\thtk\Debug\*.* C:\projects\thtk\mybin
  - 7z a -tzip C:\projects\thtk-appveyor\thtk.zip C:\projects\thtk\mybin\*
artifacts:
  path: C:\projects\thtk.zip
  name: Touhou Toolkit (git)